### ISSUE TITLE
BYOIP : support to move IP blocks across RBX, GRA, SBG

### ISSUE THREAD

**Issue by thieummm** [ovh/infrastructure-roadmap#130]
Allow the user to move its imported blocks on services located on french DCs: RBX, GRA, SBG.
This feature will be available only for newly subscribed services.

**Comment by nitefood** [comment]
Hello! Is there any possibility to allow assigning BYOIP ranges to a VRACK spanning RBX/SBG/LIM DCs? Currently that's one of out setups for a 3-nodes HA cluster based on bare metal servers (all of which support VRACK), and I'm holding off from trying the BYOIP service because (correct me if I'm wrong) once this issue gets implemented, IPs would successfully failover between RBX and SBG, but fail to failover to LIM. Is that correct? Also, failover would be only available for a whole subnet block, not single /32s (at least until #121 is also implemented). Is my understanding correct?
Looking forward to try the service!

**Comment by Seb-Renaud** [comment]
Delivered & closed
