### ISSUE TITLE
Upgrade Game processors

### ISSUE THREAD

**Issue by EvanPole** [ovh/infrastructure-roadmap#190]
Make a processor change in the gaming category which are the old Ryzen from 2020 to the new Rayzen from 2024 because they are much more efficient.
(Ryzen 9 7900X or other)

**Comment by axl303** [comment]
Can/Should we expect a upgrade to the Ryzen 9000 series until the end of the year or in the next year? R5 9600X & R7 9800X?

**Comment by HavannaFR** [comment]
No longer planned ?

**Comment by snk33** [comment]
> @HavannaFR,
> 
> #230, Unsure if the `Rise` range will have GAME stuff and will it include the newest GAME firewall (newest filters.. etc..) and network changes. Maybe. We will see when they add them.

By definition Rise range is made for second life hardware and low pricing. However, OVHcloud announced a first exception with the future Rise-N reference : https://github.com/ovh/infrastructure-roadmap/issues/230

But it won't have Game DDoS Protection because it requires specific network hardware that this range doesn't have, yet.

In the meantime, OVHcloud wants to make Game DDoS protection a network option that you'd subscribe on any dedicated server range (at least Advance/Scale/High Grade) but I'm not sure they have an ETA for this and I wouldn't bet on that.

Maybe @Denis-hamon will be able to give some details ;)

**Comment by jslocinski** [comment]
Hi,
Upgrading CPUs on old ranges is rather impossible. We won't do that.
Offering actual GAME servers as RISE ones will happen once new servers will pop-up, as explained above.
GAME DDoS Protection - this is under bigger transformation, part of which you will see in the upcoming GAME range as shared already. We can't offer backward compatibility with very old servers that's why we had to focus on delivering tomorrow's products rather than putting workload on the old ones.

No ETA for now on game firewall as general network option.. not during the next 12m.

**Comment by axl303** [comment]
@jslocinski, 

One of the questions was, will this Rise ryzens 9700x (once added), will they include GAME and most important, will they benefit from the newest game anti ddos, which is coming end of this month for some regions.

Some of our "projects"/very small communities are non-profit, so it is always good to have a bit cheaper options such as rise or sys game.
In my case I am not a target of many ddos attacks or even can't utilise all of the cores of 9700x as example.

> We see your voices here, on a github and during direct discussions and try to align with our roadmaps.

Thank you for this and the whole team for the work. Better later than never. 👍

**Comment by jslocinski** [comment]
> @jslocinski,
> 
> One of the questions was, will this Rise ryzens 9700x (once added), will they include GAME and most important, will they benefit from the newest game anti ddos, which is coming end of this month for some regions.

1/ Mentioned Rise-N servers are a different line from Rise-GAME that will come out of repricing actual GAME servers. Only GAME servers include Game DDoS Protection today.
2/ No, most of the new protections will not come for the old range due to the hardware limitations or architecture incompatibility. This move will allow us to provide future updates more frequently in coming months/years.

best regards

**Comment by jslocinski** [comment]
Recent GAME-1/2 servers are now EPYC-based which offers Ryzen performance with server-grade quality and stability.
